// <auto-generated />
using System;
using FlowVision.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowVision.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310015144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowVision.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.DeviceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmware_version");

                    b.Property<int?>("Fps")
                        .HasColumnType("integer")
                        .HasColumnName("fps");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<int?>("MemoryUsagePercent")
                        .HasColumnType("integer")
                        .HasColumnName("memory_usage_percent");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LineId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("device_logs", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CameraDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GatewayDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_device_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NominalSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("nominal_speed");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.ErrorSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LineId");

                    b.HasIndex("IsResolved", "Severity", "Timestamp");

                    b.ToTable("error_signals", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.FlowEquipment", b =>
                {
                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int?>("OverrideNominalSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("override_nominal_speed");

                    b.HasKey("FlowId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("flow_equipments", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.HourlyProduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("actual_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("HourStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Operator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<int>("RejectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_quantity");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("OrderId");

                    b.ToTable("hourly_productions", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.MachineTelemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Availability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("availability");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal>("OEE")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("oee");

                    b.Property<decimal>("Performance")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("performance");

                    b.Property<decimal>("Quality")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("quality");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Throughput")
                        .HasColumnType("integer")
                        .HasColumnName("throughput");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId", "Timestamp");

                    b.ToTable("machine_telemetry", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.OperatorAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unassigned_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("operator_assignments", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NominalSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("nominal_speed");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("production_flows", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveFlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_flow_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NominalSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("nominal_speed");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActiveFlowId");

                    b.HasIndex("SiteId");

                    b.ToTable("production_lines", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("PlannedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("produced_quantity");

                    b.Property<int>("RejectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("target_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("LineId");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CrossesMidnight")
                        .HasColumnType("boolean")
                        .HasColumnName("crosses_midnight");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("SiteId");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.ShiftOperator", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("ShiftId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("shift_operators", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_detected");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registered_by");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LineId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ShiftId");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.StopCategoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Category")
                        .IsUnique();

                    b.ToTable("stop_category_configs", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.SystemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Level", "Timestamp");

                    b.ToTable("system_logs", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FromPosition")
                        .HasColumnType("integer")
                        .HasColumnName("from_position");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("SensorDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sensor_device_id");

                    b.Property<int>("ToPosition")
                        .HasColumnType("integer")
                        .HasColumnName("to_position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("transports", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.TransportTelemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccumulationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accumulation_level");

                    b.Property<int>("AccumulationPercent")
                        .HasColumnType("integer")
                        .HasColumnName("accumulation_percent");

                    b.Property<int>("CurrentUnits")
                        .HasColumnType("integer")
                        .HasColumnName("current_units");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("TransportId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportId", "Timestamp");

                    b.ToTable("transport_telemetry", (string)null);
                });

            modelBuilder.Entity("FlowVision.API.Models.AppUser", b =>
                {
                    b.HasOne("FlowVision.API.Models.Site", "Site")
                        .WithMany("Users")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("FlowVision.API.Models.DeviceLog", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.Equipment", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany("Equipments")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.ErrorSignal", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.FlowEquipment", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany("FlowEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.ProductionFlow", "Flow")
                        .WithMany("FlowEquipments")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowVision.API.Models.HourlyProduction", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.ProductionOrder", "Order")
                        .WithMany("HourlyRecords")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FlowVision.API.Models.MachineTelemetry", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany("TelemetryHistory")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FlowVision.API.Models.OperatorAssignment", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany("OperatorAssignments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.AppUser", "User")
                        .WithMany("OperatorAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionFlow", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany("Flows")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionLine", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionFlow", "ActiveFlow")
                        .WithMany()
                        .HasForeignKey("ActiveFlowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowVision.API.Models.Site", "Site")
                        .WithMany("Lines")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveFlow");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionOrder", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionFlow", "Flow")
                        .WithMany("Orders")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany("Orders")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.Shift", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany("Shifts")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlowVision.API.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("FlowVision.API.Models.ShiftOperator", b =>
                {
                    b.HasOne("FlowVision.API.Models.Shift", "Shift")
                        .WithMany("ShiftOperators")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.AppUser", "User")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowVision.API.Models.Stop", b =>
                {
                    b.HasOne("FlowVision.API.Models.Equipment", "Equipment")
                        .WithMany("Stops")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowVision.API.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowVision.API.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Line");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FlowVision.API.Models.StopCategoryConfig", b =>
                {
                    b.HasOne("FlowVision.API.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("FlowVision.API.Models.Transport", b =>
                {
                    b.HasOne("FlowVision.API.Models.ProductionLine", "Line")
                        .WithMany("Transports")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FlowVision.API.Models.TransportTelemetry", b =>
                {
                    b.HasOne("FlowVision.API.Models.Transport", "Transport")
                        .WithMany("TelemetryHistory")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("FlowVision.API.Models.AppUser", b =>
                {
                    b.Navigation("OperatorAssignments");

                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("FlowVision.API.Models.Equipment", b =>
                {
                    b.Navigation("FlowEquipments");

                    b.Navigation("OperatorAssignments");

                    b.Navigation("Stops");

                    b.Navigation("TelemetryHistory");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionFlow", b =>
                {
                    b.Navigation("FlowEquipments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionLine", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Flows");

                    b.Navigation("Orders");

                    b.Navigation("Shifts");

                    b.Navigation("Transports");
                });

            modelBuilder.Entity("FlowVision.API.Models.ProductionOrder", b =>
                {
                    b.Navigation("HourlyRecords");
                });

            modelBuilder.Entity("FlowVision.API.Models.Shift", b =>
                {
                    b.Navigation("ShiftOperators");
                });

            modelBuilder.Entity("FlowVision.API.Models.Site", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FlowVision.API.Models.Transport", b =>
                {
                    b.Navigation("TelemetryHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
